on: [push]
env:
  MANDY_ENV: production
name: Mandy CI
jobs:
  build_and_test:
    runs-on: ubuntu-latest
    steps:
      - uses: angeldollface/mandy-github-action@v.0.1
      - name: "Verify Mandy compilation environment."
        run: echo $MANDY_ENV
      - name: "Build the site."
        run: ls && mandy -c .
